env:
  # all vars go on one line, multiple lines here triggers multiple builds, e.g.
  #  apparently DEBIAN_FRONTEND already set: http://docs.travis-ci.com/user/ci-environment/#Environment-variables
  # - DEBIAN_FRONTEND=noninteractive ALFVER=4.2.f
  # - DEBIAN_FRONTEND=noninteractive ALFVER=5.0.x
  - ALFVER=4.2.f
  - ALFVER=5.0.x

before_install:
    - sudo apt-get -yqq update
    - sudo apt-get -fyq install
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
    - wget http://apt.puppetlabs.com/puppetlabs-release-trusty.deb
    - sudo dpkg -i puppetlabs-release-trusty.deb
    - sudo apt-get update
    - sudo apt-get install git puppet -y

before_script:
    - mkdir -p modules/alfresco
    - mv files lib manifests templates modules/alfresco
    - ./install/modules-for-vagrant.sh
    - echo 'class { ''alfresco'': domain_name => ''localhost'', alfresco_version => ''${ALFVER}'', }' > go.pp

script:
    - cat go.pp
    - sudo puppet apply --debug --verbose --modulepath=modules go.pp
    - cd
    - git clone https://github.com/digcat/alfresco-tests.git
    - cd alfresco-tests
    - sudo apt-get -y upgrade
    - sudo ./install.sh 
    - sudo bash ./runtests.sh

notifications:
    irc: 
          - "chat.freenode.net#orderofthebee"

