before_install:
    - sudo apt-get -yqq update
    - sudo apt-get -fyq install
#    - cat /etc/hosts | grep -v localhost > /tmp/hosts
#   - sudo bash -c "cat /tmp/hosts > /etc/hosts"
#    - sudo bash -c 'echo "127.0.0.1 localhost docs.digcat.com" >> /etc/hosts'
#    - cat /etc/hosts
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
    - wget http://apt.puppetlabs.com/puppetlabs-release-trusty.deb
    - sudo dpkg -i puppetlabs-release-trusty.deb
    - sudo apt-get update
    - sudo apt-get install git puppet -y

before_script:
    - mkdir -p modules/alfresco
    - mv files lib manifests templates modules/alfresco
    - ./install/modules-for-vagrant.sh

script:
    - sudo puppet apply --debug --verbose --modulepath=modules go.pp

after_script:
    - cd
    - git clone https://github.com/marsbard/alfresco-tests.git
    - cd alfresco-tests
    - export DEBIAN_FRONTEND=noninteractive
    - sudo ./install.sh 
    - sudo ./runtests.sh

notifications:
    irc: 
          - "chat.freenode.net#orderofthebee"

