env:
    global:
      - TESTSRC=marsbard
      - TIMEWAIT=30
      - MAXWAITS=25
    matrix:
      - ALFVER=4.2.f
      - ALFVER=5.0.x
      - ALFVER=NIGHTLY

before_install:
    - sudo apt-get -yqq update
    - sudo apt-get -fyq install
    - "export DISPLAY=:99.0"
      #   - "sh -e /etc/init.d/xvfb start"

install:
    - wget http://apt.puppetlabs.com/puppetlabs-release-trusty.deb
    - sudo dpkg -i puppetlabs-release-trusty.deb
    - sudo apt-get update
    - sudo apt-get install git puppet -y

before_script:
    - mkdir -p modules/alfresco
    - mv files lib manifests templates modules/alfresco
    - ./install/modules-for-vagrant.sh

script:
    - install/customise-go.sh alfresco_version=$ALFVER domain_name=localhost
    - sudo puppet apply --modulepath=modules go.pp
    - install/wait-for-alfresco-ready.sh https://localhost/share $TIMEWAIT $MAXWAITS
    - cd
    - echo Using $TESTSRC tests
    - git clone https://github.com/${TESTSRC}/alfresco-tests.git
    - cd alfresco-tests
    - sudo ./install.sh 
    - sudo bash ./runtests.sh

#notifications:
#    irc: 
#      - "chat.freenode.net#orderofthebee"


