cache: apt

before_install:
  - sudo apt-get -yqq update    #< Suggested by the Travis CI doc
  - sudo apt-get -fyq install   #< Fixes inconsistency of packages installed previously

install:
  - sudo apt-get -yq install puppet #< Build Dependencies

script:
  - puppet apply manifests/init.pp

notifications:
  email:
    martin@bettercode.com
#  irc:
#    channels:
#      - "irc.freenode.org#orderofthebee"
#    on_success: always
#    on_failure: always
#    use_notice: true
