before_install:
    - sudo apt-get -yqq update
    - sudo apt-get -fyq install

install:
    - wget http://apt.puppetlabs.com/puppetlabs-release-trusty.deb
    - sudo dpkg -i puppetlabs-release-trusty.deb
    - sudo apt-get update
    - sudo apt-get install git puppet -y

before_script:
    - mkdir -p modules/alfresco
    - mv files lib manifests templates modules/alfresco
    - ./install/modules-for-vagrant.sh

script:
    - sudo puppet apply --debug --verbose --modulepath=modules go.pp

after_script:
    - cd
    - git clone https://github.com/digcat/alfresco-tests.git
    - cd alfresco-tests
    - export DEBIAN_FRONTEND=noninteractive
    - ./install.sh -e
    - ./runtests.sh

notifications:
    irc: 
          - "chat.freenode.net#orderofthebee"

