cache: apt
env: WAIT=12

language: java

before_install:
  - sudo apt-get -yqq update    #< Suggested by the Travis CI doc
  - sudo apt-get -fyq install   #< Fixes inconsistency of packages installed previously
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
#  - sudo apt-get -yq install puppet #< Build Dependencies
  - wget http://apt.puppetlabs.com/puppetlabs-release-precise.deb
  - sudo dpkg -i puppetlabs-release-precise.deb
  - sudo apt-get update 
  - sudo apt-get install puppet -y

before_script:
  - mkdir -p modules/alfresco
  - mv files lib manifests templates modules/alfresco
  - puppet module install puppetlabs-stdlib --target-dir modules
  - puppet module install puppetlabs-mysql --target-dir modules
  - puppet module install stankevich-python --target-dir modules

script:
  - sudo puppet apply --modulepath=modules go.pp
  - echo Waiting for $(( $WAIT * 10 )) seconds before running tests
  #- sleep 100 # will that be long enough? - actually do it the funky way below:
  - COUNTER=$(( $WAIT + 1)); for i in `seq 1 $WAIT`; do echo -n "$(( $COUNTER - $i))... "; sleep 10; done; echo
# this will install the testing dependencies
  - sudo puppet apply --debug --verbose --modulepath=modules test.pp
# and now run the tests: (BUT NOW THEY ARE RUN FROM test.pp)
  #- cd /opt/alfresco/tests/alfresco-tests
  #- xvfb-run python test_swsdp.py
  #- xvfb-run python test_cmis.py
  #- xvfb-run python test_ftp.py

notifications:
   email:
     - marsbard.alfresco.puppet@gmail.com
#  irc:
#    channels:
#      - "irc.freenode.org#orderofthebee"
#    on_success: change
#    on_failure: change
#    use_notice: true
