cache: apt

before_install:
  - sudo apt-get -yqq update    #< Suggested by the Travis CI doc
  - sudo apt-get -fyq install   #< Fixes inconsistency of packages installed previously

install:
#  - sudo apt-get -yq install puppet #< Build Dependencies
  - wget http://apt.puppetlabs.com/puppetlabs-release-precise.deb
  - sudo dpkg -i puppetlabs-release-precise.deb
  - sudo apt-get update 
  - sudo apt-get install puppet -y

before_script:
  - mkdir -p modules/alfresco
  - mv files lib manifests templates modules/alfresco
  - puppet module install puppetlabs-stdlib --target-dir modules
  - puppet module install puppetlabs-mysql --target-dir modules

script:
  - sudo puppet apply --modulepath=modules go.pp
  #- sleep 100 # will that be long enough? - actually do it the funky way below:
  - for i in `seq 1 10`; do echo -n "$(( 11 - $i))... "; sleep 10; done; echo
  - sudo puppet apply --modulepath=modules test.pp

notifications:
  email:
    martin@bettercode.com
#  irc:
#    channels:
#      - "irc.freenode.org#orderofthebee"
#    on_success: always
#    on_failure: always
#    use_notice: true
