cache: apt

before_install:
  - sudo apt-get -yqq update    #< Suggested by the Travis CI doc
  - sudo apt-get -fyq install   #< Fixes inconsistency of packages installed previously

install:
  - sudo apt-get -yq install puppet #< Build Dependencies

before_script:
  - pwd
  - ls
  - puppet module install puppetlabs-stdlib --target-dir modules
  - puppet module install puppetlabs-mysql --target-dir modules
  - echo 'class { alfresco: }' > go.pp

script:
  - puppet apply --modulepath=modules go.pp

notifications:
  email:
    martin@bettercode.com
#  irc:
#    channels:
#      - "irc.freenode.org#orderofthebee"
#    on_success: always
#    on_failure: always
#    use_notice: true
