cache: apt
env: WAIT=12

before_install:
  - sudo apt-get -yqq update    #< Suggested by the Travis CI doc
  - sudo apt-get -fyq install   #< Fixes inconsistency of packages installed previously

install:
#  - sudo apt-get -yq install puppet #< Build Dependencies
  - wget http://apt.puppetlabs.com/puppetlabs-release-precise.deb
  - sudo dpkg -i puppetlabs-release-precise.deb
  - sudo apt-get update 
  - sudo apt-get install puppet -y

before_script:
  - phantomjs --version
  - mkdir -p modules/alfresco
  - mv files lib manifests templates modules/alfresco
  - puppet module install puppetlabs-stdlib --target-dir modules
  - puppet module install puppetlabs-mysql --target-dir modules

script:
  - sudo puppet apply --modulepath=modules go.pp
  - echo Waiting for $(( $WAIT * 10 )) seconds before running tests
  #- sleep 100 # will that be long enough? - actually do it the funky way below:
  - COUNTER=$(( $WAIT + 1)); for i in `seq 1 $WAIT`; do echo -n "$(( $COUNTER - $i))... "; sleep 10; done; echo
  - sudo puppet apply --debug --verbose --modulepath=modules test.pp
 # this is the old way now - /opt/alfresco/tests/test.sh
  - cd /opt/alfresco/tests/alfresco-test-scripts/ABFT_4_2; sudo mvn test
  - ls -l /opt/alfresco/tests
  - ls -l /opt/alfresco/tests/alfresco-test-scripts
  - ls -l /opt/alfresco/tests/alfresco-test-scripts/ABFT_4_2

after_script:
  - cat phantomjsdriver.log | sendmail martin@ciderpunk.com


notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#orderofthebee"
#    on_success: change
#    on_failure: change
#    use_notice: true
